fun main() {
    println("Ingrese su nombre")
    val Nombre: String? = readLine()
    println("Ingrese su Edad")
    val strEdad: String? = readLine()
    println("Ingrese su Sexo")
    val strSexo: Char? = readLine()?.toCharArray()?.get(0)
    println("Ingrese su Peso")
    val strPeso: String? = readLine()
    println("Ingrese su Altura")
    val strAltura: String? = readLine()
    val PrimerObjeto = Persona(Nombre!!, strEdad!!.toInt(), strSexo!!, strPeso!!.toDouble(), strAltura!!.toInt())
    val segundoObjeto = Persona(Nombre!!, strEdad!!.toInt(), strSexo!!)
    val TercerObjeto = Persona()
    if(PrimerObjeto.CalcularIMC() == -1)
        println("Primer objeto esta bajo de peso")
    else if(PrimerObjeto.CalcularIMC() == 0)
        println("Primer objeto esta en peso ideal")
    else if(PrimerObjeto.CalcularIMC() == 1)
        println("Primer objeto tiene sobrepeso")
    if(segundoObjeto.CalcularIMC() == -1)
        println("Segundo objeto esta bajo de peso")
    else if(segundoObjeto.CalcularIMC() == 0)
        println("Segundo objeto esta en peso ideal")
    else if(segundoObjeto.CalcularIMC() == 1)
        println("Segundo objeto tiene sobrepeso")
    if(TercerObjeto.CalcularIMC() == -1)
        println("tercer objeto esta bajo de peso")
    else if(TercerObjeto.CalcularIMC() == 0)
        println("tercer objeto esta en peso ideal")
    else if(TercerObjeto.CalcularIMC() == 1)
        println("tercer objeto tiene sobrepeso")
    if(PrimerObjeto.EsMayorEdad())
        println("Primer objeto es mayor de edad")
    else
        println("Primer objeto no es mayor de edad")
    if(segundoObjeto.EsMayorEdad())
        println("segundo objeto es mayor de edad")
    else
        println("segundo objeto no es mayor de edad")
    if(TercerObjeto.EsMayorEdad())
        println("tercer objeto es mayor de edad")
    else
        println("tercer objeto no es mayor de edad")
    println("Primer objeto: \n"+ PrimerObjeto.toString())
    println("segundo objeto: \n"+ segundoObjeto.toString())
    println("Tercer objeto: \n"+ TercerObjeto.toString())
}